### ISSUE TITLE
Lỗi Thông Báo Face

### ISSUE THREAD

**Issue by NguyenTan2405** [J2TeaM/Facebook-Protector#10]
mình vừa dùng thử cái này. mình để chế độ tắt chát không online.nhưng sao mình đăng stt lên có người bình luận thì không có thông báo trên trình duyệt là sao nhỉ????

**Comment by J2TeaM** [comment]
Bạn thử tắt J2TeaM Security rồi lấy nick khác vào bình luận xem nick bạn nhận được thông báo không?

Vì mình thấy vấn đề này không liên quan gì tới các chức năng hiện tại của extension nên bạn báo lỗi như này mình cũng không tìm được nguyên nhân ở đâu.

**Comment by quocviet48** [comment]
ẩn thời gian hoạt động trong trò chuyện không hoạt động a juno ơi...
