### ISSUE TITLE
whitelist feature

### ISSUE THREAD

**Issue by thinhnat0** [J2TeaM/Facebook-Protector#12]
mong các anh xem xét thêm phần "Add to whitelist" 
mình gặp tình trang với một số trang web dịch vụ share like, sub, dù đã tắt bảo vệ thời gian thực nhưng vẫn bị J2TeaM Security chặn. cảm ơn

**Comment by J2TeaM** [comment]
Cảm ơn góp ý của em. Tính năng này cũng đang được xây dựng nhé!
